name: Release Build

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'jetbrains' # ⬅️ 修改为 jetbrains
          java-version: '21'        # ⬅️ 修改为 21

      - name: Gradle cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - name: Prepare build files
        run: |
          # 写入Google Services配置
          echo '${{ secrets.GOOGLE_SERVICES_JSON }}' > app/google-services.json

      - name: Gradle Build
        run: |
          chmod +x gradlew
          ./gradlew assembleRelease

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: release-apk
          path: app/build/outputs/apk/release/*.apk